<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Fundamentals (Need)</span></div>

# What to expect in this chapter

# 1 Functions

# 2 Python is interpreted

# 3 Python is sensitive.

# 4 Comments

# 5 = is not the same as ==

# 6 Use if to make decisions

# 7 Indentations (spaces) are sooo IMPORTANT!

# 8 ‘age’ is English, age is a variable.

# 9 Brackets

# 10 Giving Python superpowers with Packages

## 10.1 Some Context

## 10.2 Importing the math package

In [1]:
import math
math.sqrt(9)

3.0

## 10.3 Importing the numpy package

In [6]:
import numpy as np
np.sqrt([16])

array([4.])

## 10.4 Why so many packages?

In [3]:
# testing out lists
np.sqrt([4, 9, 16])

array([2., 3., 4.])

In [8]:
# trying to use lists

x = [4, 9, 16]
np.sqrt(x)

array([2., 3., 4.])

# 11 The dot (.)

In [9]:
math.sqrt(4)
np.sqrt(4)

np.float64(2.0)

In [10]:
"I am Batman".split()

['I', 'am', 'Batman']

## Footnotes